### ISSUE TITLE
The number of threads in envoy of ingress gateway is inconsistent with that configured by kubernees CPU static policy

### ISSUE THREAD

**Issue by wang-h-ng** [isiton/isiton#3]
I want to know if there is a way to configure ingress gateway to make the number of threads consistent with the k8s CPU policy

This is what my current machine looks like：
1、View the process ID used by ingress gateway
      kubectl describe pod/istio-ingressgateway-669f7ff885-68jsm -n istio-system | grep "Container ID"
            Container ID:  containerd://31fe853ee4f7c2553d8810421ffdf13ed48aabb3b979027a5161de64e306a9c6
      crictl inspect 31fe853ee4f7c2553d8810421ffdf13ed48aabb3b979027a5161de64e306a9c6 | grep pid
             "pid": 862374,
2、View the CPUID of the process binding
      taskset -c -p 862374
              pid 862374's current affinity list: 2,82
3、Number of CPUs on the node
      grep -c 'processor' /proc/cpuinfo
              160
4、View the number of envoy threads in the pod
      kubectl exec pod/istio-ingressgateway-669f7ff885-68jsm -n istio-system -- curl 127.0.0.1:15000/server_info | grep concurrency
              160

I don't know whether it will affect the CPU cache affinity of envoy in ingress gateway. Who can tell me, thank you, and how to set it to 2 to be the same as the k8s CPU policy value

**Comment by titpetric** [comment]
This is not a k8s/istio support forum.

**Comment by wang-h-ng** [comment]
ok
